### ISSUE TITLE
Checklist for registration

### ISSUE THREAD

**Issue by cvsvensson** [williamesamuelson/AffineRayleighOptimization.jl#2]
This package could eventually be released into the general registry, by following https://github.com/JuliaRegistries/General/blob/master/README.md. Before this, here's a checklist.
- [x] Implement new solver #1 
- [x] More tests. We lost some tests with more interesting matrices when we split the packages.
- [ ] Documentation. Docstrings for functions. Improve the readme. One could use [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) to make doc pages but that might be overkill for this small package.
- [x] Analyze package with [Aqua.jl](https://github.com/JuliaTesting/Aqua.jl). Could be part of CI, but not necessarily.
- [x] Analyze package with [JET.jl](https://github.com/aviatesk/JET.jl).

**Comment by williamesamuelson** [comment]
Sounds good, thanks!

**Comment by cvsvensson** [comment]
We should update Majoranas.jl to use the new interface, and see if there is any problems or not. If not, we might be ready to register the package. My only concern is that I don't like the name of the package. Wouldn't it be more technically correct that we focus on affinely constrained quadratic problems? So maybe AffineQuadraticOptimization instead?

**Comment by williamesamuelson** [comment]
Yes, I'll try to update Majoranas.jl. And AffineQuadraticOptimization sounds good to me! Not sure if I have time to take care of the renaming before my vacation though (or perhaps it's easy?).
